=== i2a2/irioCore/src/test/testSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema 
    targetNamespace="http://www.testLocation.com/test"
    xmlns="http://www.testLocation.com/test"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    elementFormDefault="qualified">

    <xs:simpleType name="RIODeviceType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="7966"/>
            <xs:enumeration value="7965"/>
            <xs:enumeration value="7961"/>
            <xs:enumeration value="9159"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="TestTypeType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="irioCore Unitary"/>
            <xs:enumeration value="irioCore Functional"/>
            <xs:enumeration value="irioCoreCpp Unitary"/>
            <xs:enumeration value="irioCoreCpp Functional"/>
            <xs:enumeration value="BFP"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="RIOSerialType">
        <xs:restriction base="xs:string">
            <xs:pattern value="0x[a-fA-F0-9]{8}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="resultsType">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d+/\d+"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="summaryType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="PASS"/>
            <xs:enumeration value="FAIL"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="couplingType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="AC"/>
            <xs:enumeration value="DC"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="moduleType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="noModule" />
            <xs:enumeration value="NI1483" />
            <xs:enumeration value="NI5761" />
            <xs:enumeration value="NI5781" />
            <xs:enumeration value="NI6581" />
            <xs:enumeration value="NI5734" />
            <xs:enumeration value="NI92xx" />
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="failedTestsType">
        <xs:sequence>
            <xs:element name="testName" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="testType">
        <xs:all>
            <xs:element name="name"              type="xs:string"/>
            <xs:element name="TestType"          type="TestTypeType"/>
            <xs:element name="TestFilter"        type="xs:string"/>
            <xs:element name="RIODevice"         type="RIODeviceType"/>
            <xs:element name="RIOSerial"         type="RIOSerialType"/>
            <xs:element name="RIOModule"         type="moduleType" />
            <xs:element name="verbose"           type="xs:boolean"      minOccurs="0"/>
            <xs:element name="coupling"          type="couplingType"    minOccurs="0"/>
            <xs:element name="maxIMAQiterations" type="xs:unsignedInt"  minOccurs="0"/>
            <xs:element name="results"           type="resultsType"     minOccurs="0"/>
            <xs:element name="summary"           type="summaryType"     minOccurs="0"/>
            <xs:element name="failedTests"       type="failedTestsType" minOccurs="0"/>
        </xs:all>
    </xs:complexType>

    <xs:element name="testplan">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="test" type="testType" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== i2a2/irioCore/src/test/test-suites/templates/irioCoreFunctional.xml
<?xml version="1.0" encoding="UTF-8"?>
<testplan
    xmlns="http://www.testLocation.com/test"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.testLocation.com/test ../testSchema.xsd">

    <!-- Common tests with both families -->
    <test>
        <name>Common FlexRIO</name>
        <TestFilter>Common.*</TestFilter>
        <TestType>irioCore Functional</TestType>
        <RIODevice>%%%COMMONDEVICE%%%</RIODevice>
        <RIOSerial>%%%COMMONSERIAL%%%</RIOSerial>
        <RIOModule>noModule</RIOModule>
        <verbose>%%%VERBOSE%%%</verbose>
    </test>
    <!-- CRIO not supported yet 
    <test>
        <name>Common cRIO</name>
        <TestFilter>Common.*</TestFilter>
        <TestType>irioCore Functional</TestType>
        <RIODevice>%%%CRIODEVICE%%%</RIODevice>
        <RIOSerial>%%%CRIOSERIAL%%%</RIOSerial>
        <RIOModule>noModule</RIOModule>
        <verbose>%%%VERBOSE%%%</verbose>
    </test> -->

    <!-- Specific tests -->
    <test>
        <name>FlexRIO Resources</name>
        <TestFilter>FlexRIOResources.*</TestFilter>
        <TestType>irioCore Functional</TestType>
        <RIODevice>%%%COMMONDEVICE%%%</RIODevice>
        <RIOSerial>%%%COMMONSERIAL%%%</RIOSerial>
        <RIOModule>noModule</RIOModule>
        <verbose>%%%VERBOSE%%%</verbose>
    </test>
    <test>
        <name>FlexRIO noModule</name>
        <TestFilter>FlexRIOnoModule.*</TestFilter>
        <TestType>irioCore Functional</TestType>
        <RIODevice>%%%COMMONDEVICE%%%</RIODevice>
        <RIOSerial>%%%COMMONSERIAL%%%</RIOSerial>
        <RIOModule>noModule</RIOModule>
        <verbose>%%%VERBOSE%%%</verbose>
    </test>
    <test>
        <name>FlexRIO DAQ</name>
        <TestFilter>FlexRIODAQ5761.*</TestFilter>
        <TestType>irioCore Functional</TestType>
        <RIODevice>%%%DAQDEVICE%%%</RIODevice>
        <RIOSerial>%%%DAQSERIAL%%%</RIOSerial>
        <RIOModule>NI5761</RIOModule>
        <verbose>%%%VERBOSE%%%</verbose>
    </test>
    <test>
        <name>FlexRIO DIO</name>
        <TestFilter>FlexRIODIO6581.*</TestFilter>
        <TestType>irioCore Functional</TestType>
        <RIODevice>%%%DIODEVICE%%%</RIODevice>
        <RIOSerial>%%%DIOSERIAL%%%</RIOSerial>
        <RIOModule>NI6581</RIOModule>
        <verbose>%%%VERBOSE%%%</verbose>
    </test>
    <test>
        <name>FlexRIO IMAQ</name>
        <TestFilter>FlexRIOIMAQ1483.*</TestFilter>
        <TestType>irioCore Functional</TestType>
        <RIODevice>%%%IMAQDEVICE%%%</RIODevice>
        <RIOSerial>%%%IMAQSERIAL%%%</RIOSerial>
        <RIOModule>NI1483</RIOModule>
        <verbose>%%%VERBOSE%%%</verbose>
    </test>
    <test>
        <name>FlexRIO UART</name>
        <TestFilter>FlexRIOUART1483.*</TestFilter>
        <TestType>irioCore Functional</TestType>
        <RIODevice>%%%IMAQDEVICE%%%</RIODevice>
        <RIOSerial>%%%IMAQSERIAL%%%</RIOSerial>
        <RIOModule>NI1483</RIOModule>
        <verbose>%%%VERBOSE%%%</verbose>
    </test>

    <!-- CRIO not supported yet 
    <test>
        <name>cRIO IO</name>
        <TestFilter>cRIO.*</TestFilter>
        <TestType>irioCore Functional</TestType>
        <RIODevice>%%%CRIODEVICE%%%</RIODevice>
        <RIOSerial>%%%CRIOSERIAL%%%</RIOSerial>
        <RIOModule>NI92xx</RIOModule>
        <verbose>%%%VERBOSE%%%</verbose>
    </test> -->

    <!-- Error tests -->
    <test>
        <name>IRIOError</name>
        <TestFilter>IRIOError.*</TestFilter>
        <TestType>irioCore Functional</TestType>
        <RIODevice>%%%COMMONDEVICE%%%</RIODevice>
        <RIOSerial>%%%COMMONSERIAL%%%</RIOSerial>
        <RIOModule>noModule</RIOModule>
        <verbose>%%%VERBOSE%%%</verbose>
    </test>

</testplan>

=== i2a2/irioCore/src/test/test-suites/irioCoreAll.xml
<?xml version="1.0" encoding="UTF-8"?>
<testplan
    xmlns="http://www.testLocation.com/test"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.testLocation.com/test ../testSchema.xsd">

    <!-- The IMAQ functional tests are grouped together to avoid
         the need of resetting the image send program -->

    <!--==================== IRIO CORE UNITARY ======================= -->
    <test>
        <name>irioCoreUnit</name>
        <TestType>irioCore Unitary</TestType>
        <TestFilter>*</TestFilter>
        <RIODevice>7966</RIODevice>
        <RIOSerial>0xFFFFFFFF</RIOSerial>
        <RIOModule>noModule</RIOModule>
        <verbose>true</verbose>
    </test>
    <!--==================== IRIO CORE CPP UNITARY =================== -->
    <test>
        <name>irioCoreCppUnit</name>
        <TestType>irioCoreCpp Unitary</TestType>
        <TestFilter>*</TestFilter>
        <RIODevice>7966</RIODevice>
        <RIOSerial>0xFFFFFFFF</RIOSerial>
        <RIOModule>noModule</RIOModule>
        <verbose>true</verbose>
    </test>
    <!--==================== IRIO CORE FUNCTIONAL ==================== -->
    <test>
        <name>Common FlexRIO</name>
        <TestFilter>Common.*</TestFilter>
        <TestType>irioCore Functional</TestType>
        <RIODevice>7966</RIODevice>
        <RIOSerial>0x0177A2AD</RIOSerial>
        <RIOModule>noModule</RIOModule>
        <verbose>true</verbose>
    </test>
    <!-- CRIO not supported yet 
    <test>
        <name>Common cRIO</name>
        <TestFilter>Common.*</TestFilter>
        <TestType>irioCore Functional</TestType>
        <RIODevice>9159</RIODevice>
        <RIOSerial>0x01DC7049</RIOSerial>
        <RIOModule>noModule</RIOModule>
        <verbose>true</verbose>
    </test> -->

    <test>
        <name>FlexRIO Resources</name>
        <TestFilter>FlexRIOResources.*</TestFilter>
        <TestType>irioCore Functional</TestType>
        <RIODevice>7966</RIODevice>
        <RIOSerial>0x0177A2AD</RIOSerial>
        <RIOModule>noModule</RIOModule>
        <verbose>true</verbose>
    </test>
    <test>
        <name>FlexRIO noModule</name>
        <TestFilter>FlexRIOnoModule.*</TestFilter>
        <TestType>irioCore Functional</TestType>
        <RIODevice>7966</RIODevice>
        <RIOSerial>0x0177A2AD</RIOSerial>
        <RIOModule>noModule</RIOModule>
        <verbose>true</verbose>
    </test>
    <test>
        <name>FlexRIO DAQ</name>
        <TestFilter>FlexRIODAQ5761.*</TestFilter>
        <TestType>irioCore Functional</TestType>
        <RIODevice>7966</RIODevice>
        <RIOSerial>0x01A34CC7</RIOSerial>
        <RIOModule>NI5761</RIOModule>
        <verbose>true</verbose>
    </test>
    <test>
        <name>FlexRIO DIO</name>
        <TestFilter>FlexRIODIO6581.*</TestFilter>
        <TestType>irioCore Functional</TestType>
        <RIODevice>7965</RIODevice>
        <RIOSerial>0x01666C59</RIOSerial>
        <RIOModule>NI6581</RIOModule>
        <verbose>true</verbose>
    </test>

    <!-- CRIO not supported yet 
    <test>
        <name>cRIO IO</name>
        <TestFilter>cRIO.*</TestFilter>
        <TestType>irioCore Functional</TestType>
        <RIODevice>9159</RIODevice>
        <RIOSerial>0x01DC7049</RIOSerial>
        <RIOModule>NI92xx</RIOModule>
        <verbose>true</verbose>
    </test> -->

    <test>
        <name>IRIOError</name>
        <TestFilter>IRIOError.*</TestFilter>
        <TestType>irioCore Functional</TestType>
        <RIODevice>7966</RIODevice>
        <RIOSerial>0x0177A2AD</RIOSerial>
        <RIOModule>noModule</RIOModule>
        <verbose>true</verbose>
    </test>


    <!--==================== IRIO CORE CPP FUNCTIONAL ==================== -->
    <test>
        <name>Common Tests</name>
        <TestFilter>CommonTests.*</TestFilter>
        <TestType>irioCoreCpp Functional</TestType>
        <RIODevice>7966</RIODevice>
        <RIOSerial>0x0177A2AD</RIOSerial>
        <RIOModule>noModule</RIOModule>
        <verbose>true</verbose>
    </test>

    <test>
        <name>Common Tests Resources</name>
        <TestFilter>CommonTestsResources.*</TestFilter>
        <TestType>irioCoreCpp Functional</TestType>
        <RIODevice>7966</RIODevice>
        <RIOSerial>0x0177A2AD</RIOSerial>
        <RIOModule>noModule</RIOModule>
        <verbose>true</verbose>
    </test>

    <test>
        <name>Common Tests Error</name>
        <TestFilter>CommonTestsError.*</TestFilter>
        <TestType>irioCoreCpp Functional</TestType>
        <RIODevice>7966</RIODevice>
        <RIOSerial>0x0177A2AD</RIOSerial>
        <RIOModule>noModule</RIOModule>
        <verbose>true</verbose>
    </test>

    <test>
        <name>FlexRIO CPUDAQ Mod6581</name>
        <TestFilter>FlexRIOCPUDAQMod6581.*</TestFilter>
        <TestType>irioCoreCpp Functional</TestType>
        <RIODevice>7965</RIODevice>
        <RIOSerial>0x01666C59</RIOSerial>
        <RIOModule>NI6581</RIOModule>
        <verbose>true</verbose>
    </test>

    <test>
        <name>FlexRIO CPUDAQ Mod5761</name>
        <TestFilter>FlexRIOCPUDAQMod5761.*</TestFilter>
        <TestType>irioCoreCpp Functional</TestType>
        <RIODevice>7966</RIODevice>
        <RIOSerial>0x01A34CC7</RIOSerial>
        <RIOModule>NI5761</RIOModule>
        <verbose>true</verbose>
    </test>

    <test>
        <name>FlexRIO CPUDAQ Mod5761 Error</name>
        <TestFilter>FlexRIOCPUDAQMod5761Error.*</TestFilter>
        <TestType>irioCoreCpp Functional</TestType>
        <RIODevice>7966</RIODevice>
        <RIOSerial>0x01A34CC7</RIOSerial>
        <RIOModule>NI5761</RIOModule>
        <verbose>true</verbose>
    </test>

    <test>
        <name>FlexRIO CPUDAQ</name>
        <TestFilter>FlexRIOCPUDAQ.*</TestFilter>
        <TestType>irioCoreCpp Functional</TestType>
        <RIODevice>7966</RIODevice>
        <RIOSerial>0x01A34CC7</RIOSerial>
        <RIOModule>NI6581</RIOModule>
        <verbose>true</verbose>
    </test>

    <test>
        <name>FlexRIO CPUDAQ Error</name>
        <TestFilter>FlexRIOCPUDAQError.*</TestFilter>
        <TestType>irioCoreCpp Functional</TestType>
        <RIODevice>7966</RIODevice>
        <RIOSerial>0x01A34CC7</RIOSerial>
        <RIOModule>NI6581</RIOModule>
        <verbose>true</verbose>
    </test>

    <!-- CRIO not supported yet 
    <test>
        <name>cRIO IO</name>
        <TestFilter>CRIOIO.*</TestFilter>
        <TestType>irioCore Functional</TestType>
        <RIODevice>9159</RIODevice>
        <RIOSerial>0x01DC7049</RIOSerial>
        <RIOModule>NI92xx</RIOModule>
        <verbose>true</verbose>
    </test> 

    <test>
        <name>CRIO CPUDAQ</name>
        <TestFilter>CRIOCPUDAQ.*</TestFilter>
        <TestType>irioCore Functional</TestType>
        <RIODevice>9159</RIODevice>
        <RIOSerial>0x01DC7049</RIOSerial>
        <RIOModule>NI92xx</RIOModule>
        <verbose>true</verbose>
    </test> -->

    <!--==================== IMAQ AND UART TESTS ==================== -->

    <test>
        <name>FlexRIO IMAQ</name>
        <TestFilter>FlexRIOIMAQ1483.*</TestFilter>
        <TestType>irioCore Functional</TestType>
        <RIODevice>7966</RIODevice>
        <RIOSerial>0x0177A2AD</RIOSerial>
        <RIOModule>NI1483</RIOModule>
        <verbose>true</verbose>
    </test>

    <test>
        <name>FlexRIO IMAQ</name>
        <TestFilter>FlexRIOCPUIMAQ.*</TestFilter>
        <TestType>irioCoreCpp Functional</TestType>
        <RIODevice>7966</RIODevice>
        <RIOSerial>0x0177A2AD</RIOSerial>
        <RIOModule>NI1483</RIOModule>
        <verbose>true</verbose>
    </test>

    <test>
        <name>FlexRIO UART</name>
        <TestFilter>FlexRIOUART1483.*</TestFilter>
        <TestType>irioCore Functional</TestType>
        <RIODevice>7966</RIODevice>
        <RIOSerial>0x0177A2AD</RIOSerial>
        <RIOModule>NI1483</RIOModule>
        <verbose>true</verbose>
    </test>

    <test>
        <name>BFP</name>
        <TestType>BFP</TestType>
        <TestFilter>*</TestFilter>
        <RIODevice>7966</RIODevice>
        <RIOSerial>0xFFFFFFFF</RIOSerial>
        <RIOModule>noModule</RIOModule>
        <verbose>true</verbose>
    </test>

</testplan>

=== i2a2/irioCore/src/test/test-suites/irioCoreFunctional.xml
<?xml version="1.0" encoding="UTF-8"?>
<testplan
    xmlns="http://www.testLocation.com/test"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.testLocation.com/test ../testSchema.xsd">

    <!-- Common tests with both families -->
    <test>
        <name>Common FlexRIO</name>
        <TestFilter>Common.*</TestFilter>
        <TestType>irioCore Functional</TestType>
        <RIODevice>7966</RIODevice>
        <RIOSerial>0x0177A2AD</RIOSerial>
        <RIOModule>noModule</RIOModule>
        <verbose>true</verbose>
    </test>
    <!-- CRIO not supported yet 
    <test>
        <name>Common cRIO</name>
        <TestFilter>Common.*</TestFilter>
        <TestType>irioCore Functional</TestType>
        <RIODevice>9159</RIODevice>
        <RIOSerial>0x01DC7049</RIOSerial>
        <RIOModule>noModule</RIOModule>
        <verbose>true</verbose>
    </test> -->

    <!-- Specific tests -->
    <test>
        <name>FlexRIO Resources</name>
        <TestFilter>FlexRIOResources.*</TestFilter>
        <TestType>irioCore Functional</TestType>
        <RIODevice>7966</RIODevice>
        <RIOSerial>0x0177A2AD</RIOSerial>
        <RIOModule>noModule</RIOModule>
        <verbose>true</verbose>
    </test>
    <test>
        <name>FlexRIO noModule</name>
        <TestFilter>FlexRIOnoModule.*</TestFilter>
        <TestType>irioCore Functional</TestType>
        <RIODevice>7966</RIODevice>
        <RIOSerial>0x0177A2AD</RIOSerial>
        <RIOModule>noModule</RIOModule>
        <verbose>true</verbose>
    </test>
    <test>
        <name>FlexRIO DAQ</name>
        <TestFilter>FlexRIODAQ5761.*</TestFilter>
        <TestType>irioCore Functional</TestType>
        <RIODevice>7966</RIODevice>
        <RIOSerial>0x01A34CC7</RIOSerial>
        <RIOModule>NI5761</RIOModule>
        <verbose>true</verbose>
    </test>
    <test>
        <name>FlexRIO DIO</name>
        <TestFilter>FlexRIODIO6581.*</TestFilter>
        <TestType>irioCore Functional</TestType>
        <RIODevice>7965</RIODevice>
        <RIOSerial>0x01666C59</RIOSerial>
        <RIOModule>NI6581</RIOModule>
        <verbose>true</verbose>
    </test>
    <test>
        <name>FlexRIO IMAQ</name>
        <TestFilter>FlexRIOIMAQ1483.*</TestFilter>
        <TestType>irioCore Functional</TestType>
        <RIODevice>7966</RIODevice>
        <RIOSerial>0x0177A2AD</RIOSerial>
        <RIOModule>NI1483</RIOModule>
        <verbose>true</verbose>
    </test>
    <test>
        <name>FlexRIO UART</name>
        <TestFilter>FlexRIOUART1483.*</TestFilter>
        <TestType>irioCore Functional</TestType>
        <RIODevice>7966</RIODevice>
        <RIOSerial>0x0177A2AD</RIOSerial>
        <RIOModule>NI1483</RIOModule>
        <verbose>true</verbose>
    </test>

    <!-- CRIO not supported yet 
    <test>
        <name>cRIO IO</name>
        <TestFilter>cRIO.*</TestFilter>
        <TestType>irioCore Functional</TestType>
        <RIODevice>9159</RIODevice>
        <RIOSerial>0x01DC7049</RIOSerial>
        <RIOModule>NI92xx</RIOModule>
        <verbose>true</verbose>
    </test> -->

    <!-- Error tests -->
    <test>
        <name>IRIOError</name>
        <TestFilter>IRIOError.*</TestFilter>
        <TestType>irioCore Functional</TestType>
        <RIODevice>7966</RIODevice>
        <RIOSerial>0x0177A2AD</RIOSerial>
        <RIOModule>noModule</RIOModule>
        <verbose>true</verbose>
    </test>

</testplan>

=== i2a2/irioCore/src/test/test-suites/templates/irioCoreCppFunctional.xml
<?xml version="1.0" encoding="UTF-8"?>
<testplan
    xmlns="http://www.testLocation.com/test"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.testLocation.com/test ../testSchema.xsd">

    <!-- Common tests with both families -->
    <test>
        <name>Common Tests</name>
        <TestFilter>CommonTests.*</TestFilter>
        <TestType>irioCoreCpp Functional</TestType>
        <RIODevice>%%%COMMONDEVICE%%%</RIODevice>
        <RIOSerial>%%%COMMONSERIAL%%%</RIOSerial>
        <RIOModule>noModule</RIOModule>
        <verbose>%%%VERBOSE%%%</verbose>
    </test>

    <test>
        <name>Common Tests Resources</name>
        <TestFilter>CommonTestsResources.*</TestFilter>
        <TestType>irioCoreCpp Functional</TestType>
        <RIODevice>%%%COMMONDEVICE%%%</RIODevice>
        <RIOSerial>%%%COMMONSERIAL%%%</RIOSerial>
        <RIOModule>noModule</RIOModule>
        <verbose>%%%VERBOSE%%%</verbose>
    </test>

    <test>
        <name>Common Tests Error</name>
        <TestFilter>CommonTestsError.*</TestFilter>
        <TestType>irioCoreCpp Functional</TestType>
        <RIODevice>%%%COMMONDEVICE%%%</RIODevice>
        <RIOSerial>%%%COMMONSERIAL%%%</RIOSerial>
        <RIOModule>noModule</RIOModule>
        <verbose>%%%VERBOSE%%%</verbose>
    </test>

    <test>
        <name>FlexRIO IMAQ</name>
        <TestFilter>FlexRIOCPUIMAQ.*</TestFilter>
        <TestType>irioCoreCpp Functional</TestType>
        <RIODevice>%%%IMAQDEVICE%%%</RIODevice>
        <RIOSerial>%%%IMAQSERIAL%%%</RIOSerial>
        <RIOModule>NI1483</RIOModule>
        <verbose>%%%VERBOSE%%%</verbose>
    </test>

    <test>
        <name>FlexRIO CPUDAQ Mod6581</name>
        <TestFilter>FlexRIOCPUDAQMod6581.*</TestFilter>
        <TestType>irioCoreCpp Functional</TestType>
        <RIODevice>%%%DAQDEVICE%%%</RIODevice>
        <RIOSerial>%%%DAQSERIAL%%%</RIOSerial>
        <RIOModule>NI6581</RIOModule>
        <verbose>%%%VERBOSE%%%</verbose>
    </test>

    <test>
        <name>FlexRIO CPUDAQ Mod5761</name>
        <TestFilter>FlexRIOCPUDAQMod5761.*</TestFilter>
        <TestType>irioCoreCpp Functional</TestType>
        <RIODevice>%%%DAQDEVICE%%%</RIODevice>
        <RIOSerial>%%%DAQSERIAL%%%</RIOSerial>
        <RIOModule>NI5761</RIOModule>
        <verbose>%%%VERBOSE%%%</verbose>
    </test>

    <test>
        <name>FlexRIO CPUDAQ Mod5761 Error</name>
        <TestFilter>FlexRIOCPUDAQMod5761Error.*</TestFilter>
        <TestType>irioCoreCpp Functional</TestType>
        <RIODevice>%%%DAQDEVICE%%%</RIODevice>
        <RIOSerial>%%%DAQSERIAL%%%</RIOSerial>
        <RIOModule>NI5761</RIOModule>
        <verbose>%%%VERBOSE%%%</verbose>
    </test>

    <test>
        <name>FlexRIO CPUDAQ</name>
        <TestFilter>FlexRIOCPUDAQ.*</TestFilter>
        <TestType>irioCoreCpp Functional</TestType>
        <RIODevice>%%%DAQDEVICE%%%</RIODevice>
        <RIOSerial>%%%DAQSERIAL%%%</RIOSerial>
        <RIOModule>NI6581</RIOModule>
        <verbose>%%%VERBOSE%%%</verbose>
    </test>

    <test>
        <name>FlexRIO CPUDAQ Error</name>
        <TestFilter>FlexRIOCPUDAQError.*</TestFilter>
        <TestType>irioCoreCpp Functional</TestType>
        <RIODevice>%%%DAQDEVICE%%%</RIODevice>
        <RIOSerial>%%%DAQSERIAL%%%</RIOSerial>
        <RIOModule>NI6581</RIOModule>
        <verbose>%%%VERBOSE%%%</verbose>
    </test>

    <!-- CRIO not supported yet 
    <test>
        <name>cRIO IO</name>
        <TestFilter>CRIOIO.*</TestFilter>
        <TestType>irioCore Functional</TestType>
        <RIODevice>%%%CRIODEVICE%%%</RIODevice>
        <RIOSerial>%%%CRIOSERIAL%%%</RIOSerial>
        <RIOModule>NI92xx</RIOModule>
        <verbose>%%%VERBOSE%%%</verbose>
    </test> 

    <test>
        <name>CRIO CPUDAQ</name>
        <TestFilter>CRIOCPUDAQ.*</TestFilter>
        <TestType>irioCore Functional</TestType>
        <RIODevice>%%%CRIODEVICE%%%</RIODevice>
        <RIOSerial>%%%CRIOSERIAL%%%</RIOSerial>
        <RIOModule>NI92xx</RIOModule>
        <verbose>%%%VERBOSE%%%</verbose>
    </test> -->


</testplan>

=== i2a2/irioCore/src/test/test-suites/irioCoreAllUnit.xml
<?xml version="1.0" encoding="UTF-8"?>
<testplan
    xmlns="http://www.testLocation.com/test"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.testLocation.com/test ../testSchema.xsd">

    <test>
        <name>BFP</name>
        <TestType>BFP</TestType>
        <verbose>false</verbose>
    </test>

    <test>
        <name>irioCoreUnit</name>
        <TestType>irioCore Unitary</TestType>
        <verbose>false</verbose>
    </test>

    <test>
        <name>irioCoreCppUnit</name>
        <TestType>irioCoreCpp Unitary</TestType>
        <verbose>false</verbose>
    </test>

</testplan>

=== i2a2/irioCore/src/test/test-suites/irioCoreUnit.xml
<?xml version="1.0" encoding="UTF-8"?>
<testplan
    xmlns="http://www.testLocation.com/test"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.testLocation.com/test ../testSchema.xsd">

    <test>
        <name>irioCoreUnit</name>
        <TestType>irioCore Unitary</TestType>
        <TestFilter>*</TestFilter>
        <RIODevice>7966</RIODevice>
        <RIOSerial>0xFFFFFFFF</RIOSerial>
        <RIOModule>noModule</RIOModule>
        <verbose>false</verbose>
    </test>

</testplan>
